"""first commit

Revision ID: c5d99a292454
Revises: 
Create Date: 2024-01-07 15:53:36.554024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5d99a292454'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userVideoProgress')
    op.drop_table('_alembic_tmp_userVideoProgress')
    op.drop_table('video_id')
    op.drop_table('videoIndex')
    with op.batch_alter_table('user_review', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_review', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    op.create_table('videoIndex',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('video_id', sa.INTEGER(), nullable=False),
    sa.Column('userVideoProgress', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['userVideoProgress'], ['userVideoProgress.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video_id',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('video_id', sa.INTEGER(), nullable=False),
    sa.Column('user_video_progress_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_video_progress_id'], ['user_video_progress.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_alembic_tmp_userVideoProgress',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('course_id', sa.VARCHAR(), nullable=False),
    sa.Column('completed', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userVideoProgress',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('course_id', sa.VARCHAR(), nullable=False),
    sa.Column('video_id', sa.INTEGER(), nullable=False),
    sa.Column('completed', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
